---
ID: "14ae4a1a-5263-4934-9474-4aa5772ba6c3"
Parent: "62806abe-7db1-4e66-a0c2-1f809d1ffa22"
Template: "c14bf746-030f-4e59-8594-395f6d299e61"
Path: /sitecore/content/sxastarter/sxastarter/Settings/Shared Sites Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230214T144048Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\srikaracharya.vatkanambi@ogilvy.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\srikaracharya.vatkanambi@ogilvy.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "eac4a6cb-d5e4-4acb-9915-54d562532183"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srikaracharya.vatkanambi@ogilvy.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230214T144048Z
