---
ID: "d5876985-423e-42a9-97fb-6b0def35a8ac"
Parent: "5f4aab16-0fe7-443a-b1f4-ea5e690b3d76"
Template: "5f4aab16-0fe7-443a-b1f4-ea5e690b3d76"
Path: /sitecore/templates/Project/sxastarter/Basic Modules/Banners/VideoBanner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230216T121225Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3435a0ee-533b-4154-8d5c-74c8855d473e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srikaracharya.vatkanambi@ogilvy.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230220T082106Z
