---
ID: "53b1113b-47e5-4e51-b1da-0561131c136a"
Parent: "b214978f-4be5-473d-9c9c-45c2b2ea7c3b"
Template: "b214978f-4be5-473d-9c9c-45c2b2ea7c3b"
Path: /sitecore/templates/Project/sxastarter/Basic Modules/IconTitleDescriptionList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230221T055350Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f5b00e7a-26db-4d4b-a9ff-caf9b24d3f11"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srikaracharya.vatkanambi@ogilvy.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230221T055350Z
