---
ID: "d3185bef-a3ca-4ae8-981f-8de4ccfc8f61"
Parent: "8c0eec13-d62c-4338-aa92-cb724d722468"
Template: "52288e39-7830-4694-b62d-32a54c6ef7ba"
Path: /sitecore/content/blogdemo/blogdemo/Presentation/Placeholder Settings
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230213T064130Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\srikaracharya.vatkanambi@ogilvy.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\srikaracharya.vatkanambi@ogilvy.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ea3a0425-b023-4b7d-a10f-69775c9b37ff"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\srikaracharya.vatkanambi@ogilvy.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230213T064130Z
